version: '3.8'

services:
  SRV-SOD-0XX-AKIRA1:
    build:
      context: .
      dockerfile: Dockerfile
    image: p100x-app:2.0.0
    container_name: SRV-SOD-0XXcuda-AKIRA1
    ports:
      - "9595:9595"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/admin_sumato/akira-edge/Database:/app/Database
      - /home/admin_sumato/akira-edge/Config:/app/Config
      - /home/admin_sumato/akira-edge/auditory:/app/auditory
    environment:
      - TZ=America/Santiago
      - AKIRAEDGE_HTTP_PORT=9595
      - AKIRAEDGE_IOT_CONN_STRING= <AZURE SECRETS>
    deploy:
      resources:
        reservations:
          memory: 50g
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 50g
    restart: unless-stopped
    network_mode: host

  SRV-SOD-0XX-AKIRA2:
    image: p100x-app:2.0.0
    container_name: SRV-SOD-0XXcuda-AKIRA2
    ports:
      - "9696:9696"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/admin_sumato/akira-edge/Database_vt:/app/Database
      - /home/admin_sumato/akira-edge/Config_vt:/app/Config
      - /home/admin_sumato/akira-edge/auditory_vt:/app/auditory
    environment:
      - TZ=America/Santiago
      - AKIRAEDGE_HTTP_PORT=9696
      - AKIRAEDGE_IOT_CONN_STRING= <AZURE SECRETS>
    deploy:
      resources:
        reservations:
          memory: 25g
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 25g
    restart: unless-stopped
    network_mode: host
