version: '3.8'

services:
  #HQ
  SRV-SOD-001-AKIRA1: 
    build:
      context: .
      dockerfile: Dockerfile
    image: p100x-app:latest
    container_name: SRV-SOD-001-AKIRA1
    ports:
      - "9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Santiago
      - AKIRAEDGE_HTTP_PORT=9090
      - AKIRAEDGE_IOT_CONN_STRING="HostName=AkiraHubProd.azure-devices.net;DeviceId=p100-sodimac-011;SharedAccessKey=XjkvxPJMjF+mzqUwnugaV0JBfXtJtDhgRP2+xVwuzwY="
    deploy:
      resources:
        reservations:
          memory: 50g
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 50g

  #VT
  SRV-SOD-001-AKIRA2: 
    build:
      context: .
      dockerfile: Dockerfile
    image: p100x-app:latest
    container_name: SRV-SOD-001-AKIRA2
    ports:
      - "9191:9191"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Santiago
      - AKIRAEDGE_HTTP_PORT=9191
      - AKIRAEDGE_IOT_CONN_STRING="HostName=AkiraHubProd.azure-devices.net;DeviceId=p100-sodimac-024;SharedAccessKey=IfJvu/YNkIGbv7YoiZxMGTWBOg2Yu096+yzWW+tVFsw="
    deploy:
      resources:
        reservations:
          memory: 25g
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 25g

#docker run --gpus all --memory=24gb --name p100x-app-01 -p 9090:9090 \
#-v /etc/localtime:/etc/localtime:ro \
#-v /etc/timezone:/etc/timezone:ro \
#-e TZ=America/Santiago \
#-e AKIRAEDGE_HTTP_PORT=9090 \
#-e AKIRAEDGE_IOT_CONN_STRING="HostName=AkiraHubProd.azure-devices.net;DeviceId=p100-sodimac-011;SharedAccessKey=XjkvxPJMjF+mzqUwnugaV0JBfXtJtDhgRP2+xVwuzwY=" p100x-app:latest
