# pyproject.toml
[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
# multi_line_output = 3 
# include_trailing_comma = true 
# force_grid_wrap = 0
# use_parentheses = true 
# ensure_newline_after_imports = true 

[tool.flake8]
max-line-length = 88
# E203 conflicts with Black's formatting. W503 is also often ignored.
# Check Flake8 documentation for docsstrings and others
extend-ignore = ["E203", "W503"]